# Setup
title:               AAIIINTT
tagline:             ''
description:         'IAINTAIT algo-sorted blog about all sorts'
url:                 http://aaiiintt.xyz
baseurl:             'https://aaiiintt.github.io/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Iain Tait
  url:               https://twitter.com/iaintait
  email:             aiin@aaiiintt.xyz

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
