# Setup
title:               AAIIINTT
tagline:             'Iain Tait's algo-sorted blog'
description:         'Blah blah blah'
url:                 https://aaiiintt.xyz
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Iain Tait
  url:               https://twitter.com/iaintait
  email:             iaintait@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
