# Setup
title:               AAIIINTT
tagline:             'The algorithmically sorted blog of Iain Tait'
description:         'Who knows what's going to happen here'
url:                 http://aaiiintt.xyz
baseurl:             ''
paginate:            10
permalink:           pretty

# About/contact
author:
  name:              Iain Tait
  url:               https://twitter.com/iaintait
  email:             aiin@aaiiintt.xyz

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.1
google_analytics_id: #UA-XXXX-Y
