# Setup
title:               AAIIINTT
tagline:             ''
description:         'IAINTAIT algo-sorted blog about all sorts'
url:                 https://aaiiintt.github.io
baseurl:             ''
paginate:            5
permalink:           pretty



# About/contact
author:
  name:              Iain Tait
  url:               https://twitter.com/iaintait
  email:             aiin@aaiiintt.xyz

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
